### PR TITLE
Added toString() and log() method to CardSet class

### PR DESCRIPTION
**Pull request by towergame**
Also fixed the toString() method in Card class, since I forgot how cards work.

### CODE REVIEW

**Review by sakars — CHANGES_REQUESTED** [review]
`case 1:
            return "A" + this.getSuitSymbol();`
here and in other places replace with static constants for readibility
(see CukasGame)

**Comment by sakars** [comment]
@Passiday this completes task 3 in projects
I suggest we move that card to "in progress"

**Comment by towergame** [comment]
> 
> 
> `case 1: return "A" + this.getSuitSymbol();`
> here and in other places replace with static constants for readibility
> (see CukasGame)


Is [this](https://github.com/Passiday/OOP-Cards/pull/9/commits/e3c8e58f5548c46baca72dfecc26d12e7b70f182) what you had in mind?

**Comment by sakars** [comment]
> > `case 1: return "A" + this.getSuitSymbol();`
> > here and in other places replace with static constants for readibility
> > (see CukasGame)
> 
> Is [this](https://github.com/Passiday/OOP-Cards/pull/9/commits/e3c8e58f5548c46baca72dfecc26d12e7b70f182) what you had in mind?

Yes exactly

**Review by sakars — APPROVED** [review]

**Comment by sakars** [comment]
> @Passiday this completes task 3 in projects
> I suggest we move that card to "in progress"

@towergame you can do that too since you are a contributor (i think)

**Comment by towergame** [comment]
Nope, no permission to edit

**Comment by Passiday** [comment]
toString() ir īpaša metode, ja objeto piespiež (coerce) konvertēties uz string (piemēram, obj+""), tad tiek netieši pasaukta objekta toString() metode.
Tāpēc es sagaidītu, ka tiek izmantots array.join(", "), nevis mahinē ar paštaisītu ciklu.

**Comment by towergame** [comment]
Njaa, taa iznaak smukaak. Es arii pie viena izdomaaju uztaisiit log() CardSetam, ceru ka labi izskataas jo vajadzeeja kaartiigi palauzt galvu kaa lai panaak ka izmet console tiesi taa, kaa vajag.

**Comment by Passiday** [comment]
Baigi sarežģītais Tev tas log() tomēr. Var taču vienkārši replace visus sarkanos simbolus ar "%c$&%c", pievienot array tik reizes, cik matchi, divus elementus - "color:red", "color:black" -, un tad pasaukt console log, izmantojot array spread operatoru (var, protams, ar apply, bet ar spread ir coolāk):
```
let params = ["color:red", "color:black", "color:blue"];
console.log("%cRed %cBlack %cBlue", ...params);
```

**Comment by towergame** [comment]
Vajadzeetu tagad buut smukaakam.

**Comment by Passiday** [comment]
Vispār jau array push() metode pieņem n parametrus, bet Ok :)

**Pull request merged**
